name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build on Ubuntu - Python 3.11
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Up Python - 3.11
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - uses: r-lib/actions/setup-pandoc@v2
        with:
            pandoc-version: '3.1.11'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Convert Markdown to HTML
        run: make html
